# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'TestApp_DataDownloader' do
    pod 'Nuke', '~> 4.0'
end
